---
title: "Inference of cellular interactions; Fig2, Suppl. Fig2 & Suppl. File 2"
author: "Aram Safrastyan"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: TRUE
    code_folding: hide
    N of_sections: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style type="text/css">
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>

# load libraries
***

```{r, pkgs, message=F, warning=F}
library(tidyverse)
library(BulkSignalR)
library(circlize)
library(magick)
library(readxl)
```

# Data preparation
***

```{r, lri, fig.width= 15, fig.height=8, warning = T, message = T, error=TRUE, eval = T}
#load Chen et al., 2022/elife LRIs
load("./data/ESCA.RData")
esca_LR <- LRinter(bsrinf) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)
load("./data/HD.RData")
hd_LR <- LRinter(bsrinf) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)
load("./data/LUAD.RData")
luad_LR <- LRinter(bsrinf) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)
load("./data/STAD.RData")
stad_LR <- LRinter(bsrinf) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)
load("./data/CRC.RData")
crc_LR <- LRinter(bsrinf) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)
load("./data/LC.RData")
lc_LR <- LRinter(bsrinf) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)
rm(bsrdm, bsrinf, scoresPathway)

# load Zhu et al., 2021/therano LRIs
load("./data/therano_lrp.RData")
hcc_therano <- LRinter(bsrinf_therano_hcc) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)
nc_therano <- LRinter(bsrinf_therano_nc) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)

#exclude LRIs found in corresponding HD cohorts
esca_nohd <- esca_LR %>% dplyr::filter(lr %in% setdiff(esca_LR$lr, hd_LR$lr))
stad_nohd <- stad_LR %>% dplyr::filter(lr %in% setdiff(stad_LR$lr, hd_LR$lr))
crc_nohd <- crc_LR %>% dplyr::filter(lr %in% setdiff(crc_LR$lr, hd_LR$lr))
luad_nohd <- luad_LR %>% dplyr::filter(lr %in% setdiff(luad_LR$lr, hd_LR$lr))
elife_lc_nohd <- lc_LR %>% dplyr::filter(lr %in% setdiff(lc_LR$lr, hd_LR$lr))
therano_lc_nohd <- hcc_therano %>% dplyr::filter(lr %in% setdiff(hcc_therano$lr, nc_therano$lr))
#same with LC intersected df
elife_therano <- lc_LR %>% dplyr::filter(lr %in% hcc_therano$lr)
elife_therano_nohd <- elife_therano %>% dplyr::filter(lr %in% hcc_therano$lr) %>% dplyr::filter(lr %in% setdiff(elife_therano$lr, c(hd_LR$lr, nc_therano$lr)))

# load scRNA-seq LRIs 
load("./data/hbv_liana_lrdb.RData")
lc_sc <- liana_test %>%
  mutate(source = recode(source, Hepatic_Stellate_Cells = "HSCs", Portal_endothelial_Cells = "PECs")) %>%
  mutate(target = recode(target, Hepatic_Stellate_Cells = "HSCs", Portal_endothelial_Cells = "PECs")) %>%
  dplyr::mutate(lr = paste0(ligand.complex, "_", receptor.complex)) %>%
  dplyr::filter(cellphonedb.pvalue < 0.05 & sca.LRscore >= 0.5)

#clean cell type names
lc_sc <- lc_sc %>%
  mutate(target = case_when(
    target == "HSCs" ~ "Hepatic stellate cells",
    target == "Macrophage" ~ "Macrophages",
    target == "NK-like_Cells" ~ "NK-like cells",
    target == "Hepatocyte" ~ "Hepatocytes",
    target == "Plasma_Cells" ~ "Plasma cells",
    target == "T_Cells" ~ "T cells",
    target == "Mature_B_Cells" ~ "Mature B cells",
    TRUE ~ target
  )) %>%
  mutate(source = case_when(
    source == "HSCs" ~ "Hepatic stellate cells",
    source == "Macrophage" ~ "Macrophages",
    source == "NK-like_Cells" ~ "NK-like cells",
    source == "Hepatocyte" ~ "Hepatocytes",
    source == "Plasma_Cells" ~ "Plasma cells",
    source == "T_Cells" ~ "T cells",
    source == "Mature_B_Cells" ~ "Mature B cells",
    TRUE ~ source
  ))
```

# Figure 2 & Suppl. Figure 2
***

```{r, figs2, fig.width= 15, fig.height=8, warning = T, message = T, error=TRUE, eval = T}
#set the pallete
cell_types <- c("Hepatocytes", "PECs", "Hepatic stellate cells", "LSECs", "Cholangiocytes", "Macrophages", "NK-like cells")
my_palette <- c('#332288', '#CC6677', '#117733', '#88CCEE', '#999933', '#44AA99', '#882255')
grid.col <- setNames(rep(my_palette, 2), c(cell_types, paste0(cell_types, " ")))

#configure the dashed line
lty_df <- data.frame(c("Hepatocytes "), c("Hepatocytes"), c(3))
lwd_df <- data.frame(c("Hepatocytes "), c("Hepatocytes"), c(3))
border_df <- data.frame(c("Hepatocytes "), c("Hepatocytes"), c(1, 1, 1))

# elife HD
pdf("./figs/chord_hd_elife.pdf", width = 10, height = 10)
par(cex=1.7)
lc_sc %>%
  dplyr::filter(lr %in% hd_LR$lr) %>%
  dplyr::count(source, target, sort = TRUE) %>%
  top_n(n = 10, wt = n) %>%
  pivot_wider(names_from = target, values_from = n) %>%
  column_to_rownames(var = "source") %>%
  `rownames<-`(paste0(rownames(.), " ")) %>%
  as.matrix() %>%
  chordDiagramFromMatrix(link.lty = lty_df, link.lwd = lwd_df, link.border = border_df, direction.type = "arrows", directional = 1, grid.col = grid.col, link.sort = TRUE, scale = TRUE)
title(main = "HD LRIs (Chen et al., 2022)", line = -0.5)
circos.clear()
dev.off()

# therano hd
pdf("./figs/chord_hd_therano.pdf", width = 10, height = 10)
par(cex=1.7)
lc_sc %>%
  dplyr::filter(lr %in% nc_therano$lr) %>%
  dplyr::count(source, target, sort = TRUE) %>%
  top_n(n = 10, wt = n) %>%
  pivot_wider(names_from = target, values_from = n) %>%
  column_to_rownames(var = "source") %>%
  `rownames<-`(paste0(rownames(.), " ")) %>%
  as.matrix() %>%
  chordDiagramFromMatrix(link.lty = lty_df, link.lwd = lwd_df, link.border = border_df, direction.type = "arrows", directional = 1, grid.col = grid.col, link.sort = TRUE, scale = TRUE)
title(main = "HD LRIs (Zhu et al., 2021)", line = -0.5)
circos.clear()
dev.off()

# elife lc
pdf("./figs/chord_lc_elife.pdf", width = 10, height = 10)
par(cex=1.7)
lc_sc %>%
  dplyr::filter(lr %in% elife_lc_nohd$lr) %>%
  dplyr::count(source, target, sort = TRUE) %>%
  top_n(n = 10, wt = n) %>%
  pivot_wider(names_from = target, values_from = n) %>%
  column_to_rownames(var = "source") %>%
  `rownames<-`(paste0(rownames(.), " ")) %>%
  as.matrix() %>%
  chordDiagramFromMatrix(link.lty = lty_df, link.lwd = lwd_df, link.border = border_df, direction.type = "arrows", directional = 1, grid.col = grid.col, link.sort = TRUE, scale = TRUE)
title(main = "LC LRIs (Chen et al., 2022)", line = -0.5)
circos.clear()
dev.off()

# Therano lc
pdf("./figs/chord_lc_therano.pdf", width = 10, height = 10)
par(cex=1.7)
lc_sc %>%
  dplyr::filter(lr %in% therano_lc_nohd$lr) %>%
  dplyr::count(source, target, sort = TRUE) %>%
  top_n(n = 10, wt = n) %>%
  pivot_wider(names_from = target, values_from = n) %>%
  column_to_rownames(var = "source") %>%
  `rownames<-`(paste0(rownames(.), " ")) %>%
  as.matrix() %>%
  chordDiagramFromMatrix(link.lty = lty_df, link.lwd = lwd_df, link.border = border_df, direction.type = "arrows", directional = 1, grid.col = grid.col, link.sort = TRUE, scale = TRUE)
title(main = "LC LRIs (Zhu et al., 2021)", line = -0.5)
circos.clear()
dev.off()

# intersected lc
pdf("./figs/chord_lc_therano_elife.pdf", width = 10, height = 10)
par(cex=1.7)
lc_sc %>%
  dplyr::filter(lr %in% elife_therano_nohd$lr) %>%
  dplyr::count(source, target, sort = TRUE) %>%
  top_n(n = 10, wt = n) %>%
  pivot_wider(names_from = target, values_from = n) %>%
  column_to_rownames(var = "source") %>%
  `rownames<-`(paste0(rownames(.), " ")) %>%
  as.matrix() %>%
  chordDiagramFromMatrix(link.lty = lty_df, link.lwd = lwd_df, link.border = border_df, direction.type = "arrows", directional = 1, grid.col = grid.col, link.sort = TRUE, scale = TRUE)
title(main = "Intersected LC LRIs (Chen et al., 2022 & Zhu et al., 2021)", line = -0.5)
circos.clear()
dev.off()

# esca
pdf("./figs/chord_esca.pdf", width = 10, height = 10)
par(cex=1.7)
lc_sc %>%
  dplyr::filter(lr %in% esca_nohd$lr) %>%
  dplyr::count(source, target, sort = TRUE) %>%
  top_n(n = 10, wt = n) %>%
  pivot_wider(names_from = target, values_from = n) %>%
  column_to_rownames(var = "source") %>%
  `rownames<-`(paste0(rownames(.), " ")) %>%
  as.matrix() %>%
  chordDiagramFromMatrix(link.lty = lty_df, link.lwd = lwd_df, link.border = border_df, direction.type = "arrows", directional = 1, grid.col = grid.col, link.sort = TRUE, scale = TRUE)
title(main = "ESCA LRIs", line = -0.5)
circos.clear()
dev.off()

# stad
pdf("./figs/chord_stad.pdf", width = 10, height = 10)
par(cex=1.7)
lc_sc %>%
  dplyr::filter(lr %in% stad_nohd$lr) %>%
  dplyr::count(source, target, sort = TRUE) %>%
  top_n(n = 10, wt = n) %>%
  pivot_wider(names_from = target, values_from = n) %>%
  column_to_rownames(var = "source") %>%
  `rownames<-`(paste0(rownames(.), " ")) %>%
  as.matrix() %>%
  chordDiagramFromMatrix(link.lty = lty_df, link.lwd = lwd_df, link.border = border_df, direction.type = "arrows", directional = 1, grid.col = grid.col, link.sort = TRUE, scale = TRUE)
title(main = "STAD LRIs", line = -0.5)
circos.clear()
dev.off()

# crc
pdf("./figs/chord_crc.pdf", width = 10, height = 10)
par(cex=1.7)
lc_sc %>%
  dplyr::filter(lr %in% crc_nohd$lr) %>%
  dplyr::count(source, target, sort = TRUE) %>%
  top_n(n = 10, wt = n) %>%
  pivot_wider(names_from = target, values_from = n) %>%
  column_to_rownames(var = "source") %>%
  `rownames<-`(paste0(rownames(.), " ")) %>%
  as.matrix() %>%
  chordDiagramFromMatrix(link.lty = lty_df, link.lwd = lwd_df, link.border = border_df, direction.type = "arrows", directional = 1, grid.col = grid.col, link.sort = TRUE, scale = TRUE)
title(main = "CRC LRIs", line = -0.5)
circos.clear()
dev.off()

# luad
pdf("./figs/chord_luad.pdf", width = 10, height = 10)
par(cex=1.7)
lc_sc %>%
  dplyr::filter(lr %in% luad_nohd$lr) %>%
  dplyr::count(source, target, sort = TRUE) %>%
  top_n(n = 10, wt = n) %>%
  pivot_wider(names_from = target, values_from = n) %>%
  column_to_rownames(var = "source") %>%
  `rownames<-`(paste0(rownames(.), " ")) %>%
  as.matrix() %>%
  chordDiagramFromMatrix(link.lty = lty_df, link.lwd = lwd_df, link.border = border_df, direction.type = "arrows", directional = 1, grid.col = grid.col, link.sort = TRUE, scale = TRUE)
title(main = "LUAD LRIs", line = -0.5)
circos.clear()
dev.off()
```

```{r, figs_old, fig.width= 15, fig.height=8, warning = T, message = T, error=TRUE, eval = F, echo=F}
#generate main fig2
img0 <- image_read_svg("./figs/chord_hd_elife.svg", width = 720)
img1 <- image_read_svg("./figs/chord_lc_elife.svg", width = 720)
combined1 <- image_append(c(img0, img1), )
image_write(combined1, "./figs/fig2.svg", )

#generate suppl. fig2
img2 <- image_read_svg("./figs/chord_crc.svg", width = 720)
img3 <- image_read_svg("./figs/chord_stad.svg", width = 720)
img4 <- image_read_svg("./figs/chord_luad.svg", width = 720)
img5 <- image_read_svg("./figs/chord_esca.svg", width = 720)
img6 <- image_read_svg("./figs/chord_hd_therano.svg", width = 720)
img7 <- image_read_svg("./figs/chord_lc_therano.svg", width = 720)
img8 <- image_read_svg("./figs/chord_lc_therano_elife.svg", width = 720)

combined1 <- image_append(c(img2, img3))
combined2 <- image_append(c(img4, img5))
combined3 <- image_append(c(combined1, combined2), stack = TRUE)
combined4 <- image_append(c(img6, img7))
combined5 <- image_append(c(combined4, img8), stack = TRUE)
combined6 <- image_append(c(combined3, combined5))
image_write(combined6, "./figs/suppl_fig2.svg")
```

# Suppl. File2
***

```{r, suppl_file2, fig.width= 15, fig.height=8, warning = T, message = T, error=TRUE, eval = T}
#elife hd
hd_cell_elife <- lc_sc %>%
  dplyr::filter(lr %in% hd_LR$lr) %>%
  dplyr::count(source, target, sort = TRUE) 

# therano hd
hd_cell_therano <- lc_sc %>%
  dplyr::filter(lr %in% nc_therano$lr) %>%
  dplyr::count(source, target, sort = TRUE)

# elife lc
lc_cell_elife <- lc_sc %>%
  dplyr::filter(lr %in% elife_lc_nohd$lr) %>%
  dplyr::count(source, target, sort = TRUE) 

# therano lc
lc_cell_therano <- lc_sc %>%
  dplyr::filter(lr %in% therano_lc_nohd$lr) %>%
  dplyr::count(source, target, sort = TRUE) 

# intersected lc
intersected_cell <- lc_sc %>%
  dplyr::filter(lr %in% elife_therano_nohd$lr) %>%
  dplyr::count(source, target, sort = TRUE)

# esca
esca_cell <- lc_sc %>%
  dplyr::filter(lr %in% esca_nohd$lr) %>%
  dplyr::count(source, target, sort = TRUE) 

# stad
stad_cell <- lc_sc %>%
  dplyr::filter(lr %in% stad_nohd$lr) %>%
  dplyr::count(source, target, sort = TRUE) 

# crc
crc_cell <- lc_sc %>%
  dplyr::filter(lr %in% crc_nohd$lr) %>%
  dplyr::count(source, target, sort = TRUE)

# luad
luad_cell <- lc_sc %>%
  dplyr::filter(lr %in% luad_nohd$lr) %>%
  dplyr::count(source, target, sort = TRUE) 

list_of_datasets <- list("N of LC cell-cell (Chen et al.)" = lc_cell_elife, "N of HD cell-cell (Chen et al.)" = hd_cell_elife, "N of LC cell-cell (Zhu et al.)" = lc_cell_therano, "N of HD cell-cell (Zhu et al.)" = hd_cell_therano, "N of LC cell-cell (intersected)" = intersected_cell, "N of ESCA cell-cell" = esca_cell, "N of STAD cell-cell" = stad_cell, "N of CRC cell-cell" = crc_cell, "N of LUAD cell-cell" = luad_cell)
write.xlsx(list_of_datasets, file = "./suppl_files/suppl_file2.xlsx")
```

```{r}
sessionInfo()
```
