---
title: "Generation of a panel of LRIs; Fig3, Suppl. Fig3 & 4, Suppl. File3"
author: "Aram Safrastyan"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: TRUE
    code_folding: hide
    number_sections: TRUE
knit: (function(input, ...) {
    )
    rmarkdown::render(
      input,
      output_dir = "./html_output"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style type="text/css">
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>

# load libraries
***

```{r, pkgs, message=F, warning=F}
library(tidyverse)
library(BulkSignalR)
library(pheatmap)
library(openxlsx)
library(viridis)
library(readxl)
library(ggpubr)
source("alluvialPlot.R")
```

# Data preparation
***

```{r, lri, fig.width= 15, fig.height=8, warning = T, message = T, error=TRUE, eval = T}
load("./data/ESCA.RData")
esca_LR <- LRinter(bsrinf) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)
load("./data/HD.RData")
hd_LR <- LRinter(bsrinf) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)
load("./data/LUAD.RData")
luad_LR <- LRinter(bsrinf) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)
load("./data/STAD.RData")
stad_LR <- LRinter(bsrinf) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)
load("./data/CRC.RData")
crc_LR <- LRinter(bsrinf) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)
load("./data/LC.RData")
lc_LR <- LRinter(bsrinf) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)
rm(bsrdm, bsrinf, scoresPathway)

# load Zhu et al., 2021/therano LRIs and choose significant LRIs
load("./data/therano_lrp.RData")
hcc_therano <- LRinter(bsrinf_therano_hcc) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)
nc_therano <- LRinter(bsrinf_therano_nc) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)

# load scRNA-seq LRIs and choose significant LRIs
load("./data/hbv_liana_lrdb.RData")
lc_sc <- liana_raw %>%
  dplyr::mutate(lr = paste0(ligand.complex, "_", receptor.complex)) %>%
  dplyr::filter(cellphonedb.pvalue < 0.05 & sca.LRscore >= 0.5)

# load bulk RNA-seq LRIs and choose significant LRIs
load("./data/gse_liver_res.RData")
lc_bulk <- LRinter(bsrinf_hcc) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001 & LR.corr >= 0.5)
```

# Figure 3
***

```{r, fig3, fig.width= 15, fig.height=8, warning = T, message = T, error=TRUE, eval = T}
a <- lc_LR %>%
  dplyr::filter(!(lr %in% c(hd_LR$lr, stad_LR$lr, esca_LR$lr, stad_LR$lr, crc_LR$lr, luad_LR$lr, nc_therano$lr)) & (lr %in% lc_bulk$lr | lr %in% lc_sc$lr)) %>%
  dplyr::filter(lr %in% hcc_therano$lr) %>%
  distinct(lr, .keep_all = T)
# calculate the average expression of the ligands and receptors of the panel in the scRNA-dataset per cell type
## load the sc data
load("./data/hbv_sc_seurat.RData")
av_expr <- AverageExpression(object = seurat_object, features = c(a$L, a$R), return.seurat = F)$RNA %>%
  as.data.frame() %>%
  rownames_to_column(var = "genes")
# designate ligands and receptors
av_expr1 <- av_expr %>%
  inner_join(., a, by = c("genes" = "L")) %>%
  dplyr::select(-c(14:22))

# get the pathway names
## filter elife and therano LC dfs for panel list and bind
elife_a <- lc_LR %>% dplyr::filter(lr %in% a$lr)
therano_a <- hcc_therano %>% dplyr::filter(lr %in% a$lr)
elife_therano_a <- rbind(elife_a, therano_a)
## choose the pathways with most genes
a_min <- elife_therano_a %>%
  group_by(lr) %>%
  filter(len == max(len)) %>%
  ungroup() %>%
  distinct(lr, .keep_all = TRUE)
## shorten the pathway name for visualization purposes
a_min <- a_min %>%
  mutate(pw.name = recode(pw.name, "Regulation of Insulin-like Growth Factor (IGF) transport and uptake by Insulin-like Growth Factor Binding Proteins (IGFBPs)" = "Regulation of IGF transport and uptake by IGFBPs"))
# restructure the data for plotting
av_expr2 <- inner_join(av_expr1, av_expr, by = c("R" = "genes")) %>%
  dplyr::rename("L" = "genes") %>%
  dplyr::mutate(lr = paste0(L, " ", "->", " ", R)) %>%
  dplyr::mutate(lr1 = paste0(L, "_", R)) %>%
  arrange(match(lr1, a_min$lr)) %>%
  dplyr::select(-c(lr1, L, R)) %>%
  column_to_rownames(var = "lr")

# prepare for plotting
col.subsections <- c(11, 11)
col_split <- data.frame(rep(c("Ligand Expression", "Receptor Expression"), col.subsections))
c <- factor(a_min$pw.name)
text_list <- list(
  text1 = levels(c)[1],
  text2 = levels(c)[2],
  text3 = levels(c)[3],
  text4 = levels(c)[4],
  text5 = levels(c)[5],
  text6 = levels(c)[6],
  text7 = levels(c)[7],
  text8 = levels(c)[8],
  text9 = levels(c)[9],
  text10 = levels(c)[10]
)
ha <- rowAnnotation(foo = anno_empty(
  border = FALSE,
  width = max_text_width(unlist(text_list)) + unit(4, "mm")
))
# plot the main heatmap
draw(Heatmap(as.matrix(av_expr2), name = "Average Expression", cluster_rows = FALSE, cluster_columns = FALSE, column_split = col_split$rep.c..Ligand.Expression....Receptor.Expression....col.subsections., row_names_side = "left", column_names_rot = 45, column_gap = unit(.02, "npc"), column_labels = c("T Cells", "Macrophages", "LSECs", "NK-like Cells", "Portal Endothelial Cells", "Hepatic Stellate Cells", "Hepatocytes", "Mature B Cells", "Erythroid Cells", "Plasma Cells", "Cholangiocytes", "T Cells", "Macrophages", "LSECs", "NK-like Cells", "Portal Endothelial Cells", "Hepatic Stellate Cells", "Hepatocytes", "Mature B Cells", "Erythroid Cells", "Plasma Cells", "Cholangiocytes"), col = colorRamp2(c(0, 2, 4), hcl_palette = "Blue-Red 2"), heatmap_legend_param = list(
  legend_direction = "horizontal", labels_gp = gpar(fontsize = 11), title_gp = gpar(fontsize = 11, fontface = "bold"),
  legend_width = unit(8, "cm")
), row_split = c, right_annotation = ha, row_title = NULL), heatmap_legend_side = "bottom", )
# add the rownames (i.e., pathway names)
for (i in 1:10) {
  decorate_annotation("foo", slice = i, {
    grid.rect(x = 0, width = unit(2, "mm"), gp = gpar(fill = i, col = NA), just = "left")
    grid.text(paste(text_list[[i]], collapse = "\n"), x = unit(4, "mm"), just = "left")
  })
}
```

# Suppl. Fig3
***

```{r, suppl_fig3, fig.width= 15, fig.height=8, warning = T, message = T, error=TRUE, eval = T}
serpinc1_expr <- read_excel("data/genes_exp.xlsx", sheet = "Sheet1") %>% dplyr::rename(cancer = `...1`)
gpc3_expr <- read_excel("data/genes_exp.xlsx", sheet = "Sheet2") %>% dplyr::rename(cancer = `...1`)
p1 <- serpinc1_expr %>% pivot_longer(names_to = "Source", values_to = "TPM", !cancer) %>%  ggplot(., aes(x = cancer, y = TPM, fill = Source)) + geom_bar(stat="identity", position = "dodge") + scale_fill_manual(values = c(Tumor = "red", Normal = "blue")) + ylab("TPM (SERPINC1)") + theme_pubclean(base_size = 18, base_family = "Helvetica") + theme(plot.title = element_text(hjust = 0.5, vjust = 2.5, face = "bold", size = 20), axis.text.x = element_text(angle = 30, family = "Helvetica", hjust = 1, vjust = 1), axis.title.x = element_blank())
p2 <- gpc3_expr %>% pivot_longer(names_to = "Source", values_to = "TPM", !cancer) %>%  ggplot(., aes(x = cancer, y = TPM, fill = Source)) + geom_bar(stat="identity", position = "dodge") + scale_fill_manual(values = c(Tumor = "red", Normal = "blue")) + ylab("TPM (GPC3)") + theme_pubclean(base_size = 18, base_family = "Helvetica") + theme(plot.title = element_text(hjust = 0.5, vjust = 2.5, face = "bold", size = 20), axis.text.x = element_text(angle = 30, family = "Helvetica", hjust = 1, vjust = 1), axis.title.x = element_blank())
p3 <- ggarrange(p1, p2, labels = "AUTO", nrow = 2, hjust = -1, vjust = -0.1, font.label = list(size = 20, family = "Helvetica"), common.legend = T)
ggsave(plot = p3, file = "./figs/suppl_fig3.jpg", units = "mm", device = "jpeg", height = 180, width = 350, scaling = 1, limitsize = FALSE)
```

# Suppl. Fig4
***

```{r, suppl_fig4, fig.width= 15, fig.height=8, warning = T, message = T, error=TRUE, eval = T}
cite_lri <- read_excel("data/cite.xlsx") %>% dplyr::rename(tme = `...1`) %>% janitor::clean_names(case = "all_caps") 
cite_lri <- cite_lri[, c("TME", intersect(a, colnames(cite_lri)))] %>% column_to_rownames(var = "TME")
pheatmap(cite_lri, cluster_rows = F, cluster_cols = F, angle_col = 45, labels_row = c("cancer-cancer", "cancer-stroma", "normal-normal", "stroma-cancer", "stroma-stroma"), labels_col = str_replace(colnames(cite_lri), "_", "-"), filename = "./figs/suppl_fig4.pdf", width = 15)
```

# Suppl. File3
***

```{r, suppl_file3, fig.width= 15, fig.height=8, warning = T, message = T, error=TRUE, eval = T}
list_of_datasets <- list("Panel(Chen et al+Zhu et al)" = elife_therano_a)
write.xlsx(list_of_datasets, file = "./suppl_files/suppl_file3.xlsx")
```

```{r}
sessionInfo()
```
